---
title: "Problema 1 CP 3 "
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---


```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```

```{r}
data = read_csv(here("data/series_from_imdb.csv"), progress = FALSE,
                    col_types = cols(.default = col_double(), 
                                     series_name = col_character(), 
                                     episode = col_character(), 
                                     url = col_character(),
                                     season = col_character()))
```

```{r}
data_long = data %>%
    group_by(series_name) %>% 
    summarize_at(vars(r1:r10), funs(mean)) %>% 
    gather("rating", "proporcao", 2:11)
```

```{r}
data_long %>%
    filter(series_name %in% c("Mr Robot", "American Idol", "American Dad")) %>% 
    ggplot(aes(x = series_name, y = rating, color = series_name, size = proporcao)) + 
      geom_point()
```


Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
